language: node_js
node_js: 8
script:
- cd frontend
- yarn install
- yarn build
- cd ../backend
- cp -r ../frontend/dist ./
deploy:
  skip_cleanup: true
  provider: heroku
  app: bloglist-fullstack-app
  api_key:
    secure: StcaG3/mUFmmTjaHJyPVwwpokBLgyQw+i5Smxge/A+PYpSFTXC+PH6pE3tf2qHFO3n3BERfV2HXPuQkmNWYvJvFTDPfdcU8LZa04ymzMdwkaRtXHhG087LwvFQtpGYJUYN40QTuVgqFSZVFZ7h8Eo5xKJ1Hj3lo1PYIB4l9dGIH8ReMapMznZ30EdMtrX6Pp9No/8BV0q1pBXwQwvLf7GAzZEAo9PirAagFgHg2bT+PyKba2nxOXZ3B9QVwxNLZgSy8IlvnMz1lxLuvxzMrY194rUKZ6F1Y4XB3y5D8omEtbCfREwX6O0/DpUplB88G5d+p8419c6y1RJ0G3W4rN6l/f72jpDovwsHlGXnKgIZ4MYwiJ6EvJJIJOgHiUeeViniD3z+T3wWHCnrZu6wVLZIGcPlKl8K9Qaewt0K88oboKPBRix1fhEDGKOI0hMZRKCgt0M7u9d/IXpKLPwUjzFLLc9ttMY/idnDbWcwVk1Xo22ZAJAuXWe5Yj4meRbqwYLU03eoMt1qYsD4k24Ox82oCnH7EZo+ep6APpCg2V/LS9IXYSsMDyTilnZpB8/ycagk3V1qpgupNE3+RafF/QiW12Y5152Dwq8RtXsPOjgO1X6XK3NIJu7HmmAeVhY8CJmWkxGIuvoaiO+ENdPm/Z1dHsLv+ZB3CnHyAWt52jMiY=
cache: yarn
